### ISSUE TITLE
Spatial filtering of data for retrospective analysis

### ISSUE THREAD

**Issue by AngeliaMiller** [thefaylab/sseep-analysis#7]
For each species and season
- [x] find total biomass by strata
-- sum(EXPCATCHWT) 
- [x] arrange(strata) in desc/ascending order based on sum(EXPCATCHWT) 
- [x] find cumulative distribution for each species and season 
-- ungroup, sum(EXPCATCHWT)
- [x] Find strata and sum(EXPCATCHWT)  [from step 1 & 2) that equals 95% of cumulative distribution (step 3)
-- select(strata != c())

**Comment by AngeliaMiller** [comment]
@gavinfay, 

I started an `analysis-testing` branch in order to work on this and changes to the sdmtmb code. Can you take a look at the `spatial-filter.R` script in the branch added by commit [cf4ff1c](https://github.com/thefaylab/sseep-analysis/commit/cf4ff1c25ab0d8317c974b62df0ba8a2ed24be98) when you have a chance? 

I tested some cumulative distribution code on a subset of summer flounder total biomass data, and want to ensure this is what you envisioned for finding the cumulative distribution of biomass in step 3, before moving on to step 4. 

Thanks!

**Comment by gavinfay** [comment]
@AngeliaMiller I think once you've ordered the strata from highest biomass to lowest, create a vector with the cumulative sum (e.g. with `cumsum()` within groups and then divide this by the total for each group. You can then remove strata where this proportion is >0.95. Think this is easier than using `ecdf()` which is helpful for generating from the cdf.

**Comment by AngeliaMiller** [comment]
@gavinfay please see commit [8c5e646](https://github.com/thefaylab/sseep-analysis/commit/8c5e646fb9f29f750e7b2dff618dbe1e6d927533) with changes to `spatial-filter.R` incorporating the `cumsum()` function and dividing the sums by the maximum cumulative sum to derive the proportions on my test data frame (fall summer flounder biomass by strata). 

Let me know if this is more in line with what you're expecting to see! If so, I can apply to all the other species and seasons and go from there. 

Thanks!

**Comment by gavinfay** [comment]
Right, yes and then you can look at the results of the strata selection based on different thresholds. (e.g. what does the spatial footprint look like if you use top 95% catch vs top 99%, etc.)

Couple notes (neither critical):
- don't think you need to order the data frame by stratum, just by catch. (the strata numbers are just labels)
- could do all in one step:  cumsum(x)/sum(x)

**Comment by AngeliaMiller** [comment]
I filtered the complete dataset (3962124 obs) based on strata selection with the top 95% and the top 99% biomass using the the code found in commit [c0c937d](https://github.com/thefaylab/sseep-analysis/commit/c0c937d473c7ae5c9d1ba2b81e7f8999ad0098c5).

This resulted in datasets that are 7% (282107 obs out of 3962124 obs) and 10% (424559 obs out of 3962124 obs) of the full dataset, respectively. 

Thoughts?

**Comment by AngeliaMiller** [comment]
95% and 99% cumulative distributions have been calculated for each species, and season combination across strata. The 99% distribution based on strata was used to filter the complete dataset tidied through `02-complete-datasets.R` for each species and season. The filtered dataset was saved and will be used in subsequent analyses such as the retrospective analysis and the sdmTMB model fits. 

Scripts can currently be found in the `data-cleaning` branch under the `tidy-data` folder. A pull request is still needed into the main branch.

**Comment by AngeliaMiller** [comment]
95% threshold filters out 107 species from the data frame, while 99% threshold filters out 100 species from the data frame. 

Tables of species that were filtered out based on the 95% threshold ([spec95_comp.csv](https://github.com/thefaylab/sseep-analysis/files/10787584/spec95_comp.csv)), and the 99% threshold ([spec99_comp.csv](https://github.com/thefaylab/sseep-analysis/files/10787586/spec99_comp.csv)).

**Comment by gavinfay** [comment]
I don't see why this operation is removing species - you are choosing the strata to analyze for each species.
I suppose that if a species had only ever been observed in tows conducted in a single stratum then the entire cdf would be 1, and so no strata would be below your threshold. Looking at your list of species I could see this might be true for some of the megafauna that might have been caught by accident on occasion (e.g. porpoise), but not likely for other species.

**Comment by AngeliaMiller** [comment]
Hi Gavin, 

Below are the plots you mentioned in our meeting today - the number of strata (where biomass is greater than 0) in which a species is caught. I pulled the seasons out into separate plots rather than facet wrapping due to the number of species. 

Here also is: 
 - a dataframe containing the [strata counts for all species and each season](https://github.com/thefaylab/sseep-analysis/files/10853166/species_strata_ct.csv), in which the plots are derived from. 
 - a dataframe containing the [strata counts for each species that was filtered out by the 95% threshold and each season](https://github.com/thefaylab/sseep-analysis/files/10853322/strata_comp95.csv); and
 - a dataframe containing the [strata counts for each species that was filtered out by the 99% threshold and each season](https://github.com/thefaylab/sseep-analysis/files/10853323/strata_comp99.csv)

Let me know your thoughts. Thanks! 

![fall_strata_ct](https://user-images.githubusercontent.com/83592135/221931790-59fa6179-93f5-437b-8e0a-0e927b18bb3c.png)

![spring_strata_ct](https://user-images.githubusercontent.com/83592135/221931803-c85bc839-3619-45ac-b2b2-c9369c361113.png)

**Comment by AngeliaMiller** [comment]
Commit [f175f20](f175f20e5fcc34a27fe64e42c5f2acb503c045d6) adds scripts `03a-create-spatial-filter.R`, and `03b-spatial-filter-data.R` to filter observations for each species and season based on criteria: 

- observed in 3 or more strata
- observed in 3 or more years 
- observed in strata with potential impact from offshore wind areas 

 `spatial-filter-vis.R` under the commit, creates seasonal plots of the cumulative distribution of each species filtered above.
